### ISSUE TITLE
连接服务器失败

### ISSUE THREAD

**Issue by Wxianpeng** [fighter-lee/EasyMqtt#11]
报错日志 ：
![image](https://user-images.githubusercontent.com/45260591/64689513-12298b80-d4c1-11e9-9ef6-9dec0b68ef94.png)

windows客户端

![image](https://user-images.githubusercontent.com/45260591/64689578-34bba480-d4c1-11e9-9381-98c7e05565df.png)

**Comment by fighter-lee** [comment]
1.clientID不能重复;
2.确认设备能否ping通这个ip；
3.确认用户名密码是否正确；
